name: adb_wifi_plus
description: A Windows-friendly CLI for attaching adb over Wi-Fi using a QR code, with automatic adb connect after pairing.
version: 1.0.0
repository: https://github.com/nadershoulan/adb_wifi_for_windows
issue_tracker: https://github.com/nadershoulan/adb_wifi_for_windows/issues

environment:
  sdk: ^3.4.1

dependencies:
  multicast_dns: ^0.3.3
  nanoid: ^1.0.0
  qr: ^3.0.2

dev_dependencies:
  very_good_analysis: ^6.0.0

executables:
  adb_wifi_plus: adb_wifi
